server:
  port: 9001
spring:
  #  datasource:
  #    url: jdbc:h2:mem:mcommande
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5432/mcommande
    username: postgres
    password: 123456a.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #      update, create, create-drop
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  #  mvc:
  #    throw-exception-if-no-handler-found: true
  #    static-path-pattern: /static
  application:
    name: mcommande
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9102/eureka/
#  h2:
#    console:
#      enabled: true
